name: deposits_ui_kit
description: Deposits UI Kit is a library with pre-built components, speeding up financial application development and making customization easy..
version: 0.0.7
homepage: https://github.com/DepositsTeam/Flutter-UI-Kit/tree/dev

environment:
  sdk: '>=2.19.1 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  another_flushbar: ^1.12.29
  form_builder_validators: ^9.1.0
  flutter_form_builder: ^9.1.1
  linear_progress_bar: "^1.1.0"
  fl_chart: ^0.64.0
  dropdown_search2: ^1.0.2
  currency_text_input_formatter: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.deposits_ui_kit.deposits_ui_kit
        pluginClass: DepositsUiKitPlugin
      ios:
        package: com.deposits_ui_kit.deposits_ui_kit
        pluginClass: DepositsUiKitPlugin
      linux:
        pluginClass: DepositsUiKitPlugin
      macos:
        pluginClass: DepositsUiKitPlugin
      windows:
        pluginClass: DepositsUiKitPluginCApi

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/custom_json/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: HeroNew
      fonts:
        - asset: assets/fonts/Hero-New-Bold.ttf
        - asset: assets/fonts/Hero-New-SemiBold.ttf
        - asset: assets/fonts/Hero-New-Regular.ttf
        - asset: assets/fonts/Hero-New-Thin.ttf

    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.ttf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.ttf
          weight: 700

    - family: SFProRounded
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Rounded-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Rounded-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Rounded-Bold.otf
          weight: 700

    - family: SFProText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700

    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd-Black.ttf
        - asset: assets/fonts/CircularStd-Bold.ttf
        - asset: assets/fonts/CircularStd-Book.ttf
        - asset: assets/fonts/CircularStd-Medium.ttf
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
